### PR TITLE
Update app.json

### PR DESCRIPTION
**Pull request by Hariharanhariharan**
https://github.com/Hariharanhariharan/HN--RENAME-BOT

### CODE REVIEW

**Comment by Hariharanhariharan** [comment]
https://github.com/Hariharanhariharan/HN--RENAME-BOT

**Comment by Hariharanhariharan** [comment]
https://github.com/Hariharanhariharan/HN--RENAME-BOT

**Comment by Hariharanhariharan** [comment]
Hi

**Comment by Hariharanhariharan** [comment]
https://t.me/HariTv05

**Comment by Mhdrzn** [comment]
Invalid

**Pull request closed without merging**
